### ISSUE TITLE
Codereview bug in arena_grow, maybe?

### ISSUE THREAD

**Issue by aghast** [olemorud/arena-allocator#1]
https://github.com/olemorud/arena-allocator/blob/44a2982376cc80e7a0637009c1a070d59012a5e6/src/arena.c#L23

^^ In the code above, you call mprotect() with a size of (capacity * 2), but you are using the end of the buffer as the starting point. Thus, the read/writable region of memory becomes [dirty arena][2*capacity new pages], for a total of 3x as much space. 

However, a few lines down you adjust capacity by x2, which means you "leak" some of the newly-mprotect()ed memory, since you tagged it but are ignoring it because of how capacity is adjusted.

(I think you are doing this thing in a straightforward way. If so, I think this is a bug. But I'm just a passer-by reading through your arena code, so I may be missing something.)

If you agree this is a bug, you could probably fix it by adding to the capacity, instead of multiplying it:

    a->cap += a->cap * 2;   // Where "2" is a macro I do not remember

**Comment by olemorud** [comment]
you are right, thanks!
